wp_maker:
  _target_: derive_wp.WPMaker

  wp_definitions:
    e:
      wp_names: ["VVTight", "VTight", "Tight", "Medium", "Loose", "VLoose", "VVLoose", "VVVLoose"]
      wp_eff: [0.6, 0.7, 0.8, 0.9, 0.95, 0.98, 0.99, 0.995]
    mu:
      wp_names: ["Tight", "Medium", "Loose", "VLoose"]
      wp_eff: [0.995, 0.998, 0.999, 0.9995]
    jet:
      wp_names: ["VVTight", "VTight", "Tight", "Medium", "Loose", "VLoose", "VVLoose", "VVVLoose"]
      wp_eff: [0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 0.95, 0.98]
    
  tpr_step: 0.0001 # will evenly sample grid of values from 0 to 1 with step=tpr_step
  require_wp_vs_others: True # whether 

create_df:
  _target_: derive_wp.create_df

  # path to prediction files
  _path_to_mlflow: ???
  _experiment_id: ???
  _run_id: ???
  path_to_preds: "${_path_to_mlflow}/${_experiment_id}/${_run_id}/artifacts/predictions/"
  pred_samples:
    GluGluHToTauTau_M125: 'eventTuple_1-7_pred.h5' # lists and * are supported 
  
  # paths to input ROOT files will be retrieved from corresponding pred_input_filemap.json
  input_branches: [ 'tau_pt', 'tau_eta', 'tau_decayMode' ]
  input_tree_name: taus
  selection: '(tau_pt>=20) and (tau_pt<100)'
  tau_types: ['e', 'mu', 'tau', 'jet']