defaults: # import plotting configuration
  - wp_eff_var@_global_: ???
  - _self_

vs_type: jet
pred_samples: # factorised from create_df() args for partial calls per tau_type
  tau:
    GluGluHToTauTau: 'eventTuple_1-*_pred.h5'
  jet:
    TTToSemiLeptonic: 'eventTuple_1-*_pred.h5'

require_wp_vs_others: True # whether to apply additional selection to pass `WPs_to_require` (all except the one for `vs_type`)
WPs_to_require:
  e: VVVLoose
  mu: VLoose
  jet: VVVLoose

create_df: # dataframe composition
  _target_: functools.partial # to instantiate a partial create_df() object 
  _args_: ["${get_method:__main__.create_df}"]

  # path to prediction files
  path_to_mlflow: ???
  experiment_id: ???
  run_id: ???
  path_to_preds: "${create_df.path_to_mlflow}/${create_df.experiment_id}/${create_df.run_id}/artifacts/predictions/"
  
  # paths to input ROOT files will be retrieved from corresponding pred_input_filemap.json
  input_branches: [ 'tau_pt', 'tau_eta', 'tau_phi', 'tau_dz', 'tau_decayMode' ]
  input_tree_name: taus
  selection: '(tau_pt>=20) and (tau_pt<1000) and (abs(tau_eta) < 2.3) and (abs(tau_dz) < 0.2) and not (tau_decayMode in [5,6])'

output_filename: wp_eff/plots/test.png # as /path/within/mlflow/artifacts/filename.png