# general
name: DeepTau vs. ${vs_type} (v2p1)
color: blue
dashed: False
raw: True

# prediction/target columns
pred_column_prefix: node_
pred_column: tau_byDeepTau2017v2p1VS${vs_type}raw # column in internally created pd.DataFrame to be used for metrics computation  

# WPs
wp_from: wp_column
wp_column: tau_byDeepTau2017v2p1VS${vs_type}
working_points: ${.working_points_map.${vs_type}} 
working_points_map: 
  e:
    - ${wp_name_to_index.VVVLoose}
    - ${wp_name_to_index.VVLoose}
    - ${wp_name_to_index.VLoose}
    - ${wp_name_to_index.Loose}
    - ${wp_name_to_index.Medium}
    - ${wp_name_to_index.Tight}
    - ${wp_name_to_index.VTight}
    - ${wp_name_to_index.VVTight}
  mu:
    - ${wp_name_to_index.VLoose}
    - ${wp_name_to_index.Loose}
    - ${wp_name_to_index.Medium}
    - ${wp_name_to_index.Tight}
  jet:
    - ${wp_name_to_index.VVVLoose}
    - ${wp_name_to_index.VVLoose}
    - ${wp_name_to_index.VLoose}
    - ${wp_name_to_index.Loose}
    - ${wp_name_to_index.Medium}
    - ${wp_name_to_index.Tight}
    - ${wp_name_to_index.VTight}
    - ${wp_name_to_index.VVTight}
