# general 
name: MVA vs. jets (JINST 13 (2018) P10005)
color: green
dashed: False
raw: False

# prediction/target columns
pred_column_prefix: node_
pred_column: null

# WPs
wp_from: wp_column
wp_column: tau_byIsolationMVArun2017v2DBoldDMwLT2017
working_points: 
  - ${wp_name_to_index.VVLoose}
  - ${wp_name_to_index.VLoose}
  - ${wp_name_to_index.Loose}
  - ${wp_name_to_index.Medium}
  - ${wp_name_to_index.Tight}
  - ${wp_name_to_index.VTight}
  - ${wp_name_to_index.VVTight}
