Setup:
    n_tau                :  500
    start_dataset        :  0
    end_dataset          :  9999999999999 #std::numeric_limits<Long64_t>::max()
    iso_cone             :  0.5
    n_inner_cells        :  11
    inner_cell_size      :  0.02
    n_outer_cells        :  21
    outer_cell_size      :  0.05
    n_threads            :  1
    # tau_types_names.keys are written in accordance with tauType in the tau tuple
    tau_types_names      : { "0":"e", "1":"mu", "2":"tau", "3":"jet" }
    input_dirs           : ["/eos/user/m/myshched/LawTest_flush10_virt10_v3/"]
    file_name_pattern    : "^.*_(21|22|23|24|25|26|27|28|29).root$"
    exclude_list         : ""
    exclude_dir_list     : ""
    input_spectrum       : "/eos/home-m/myshched/ShuffleSpectrum.root"
    target_spectrum      : "/eos/home-m/myshched/ShuffleSpectrum.root"
    n_pt_bins            : 49
    pt_min               : 20.0
    pt_max               : 1000.0
    n_eta_bins           : 4
    eta_min              : 0.0
    eta_max              : 2.3
    weight_thr           : 100000.0
    # here define variables for the Histogram_2D class
    xaxis_vec            : [0., 0.625, 1.25, 1.875, 2.5]
    yaxis_list_vec       : [[20., 40., 60., 100., 1000.], [20., 60., 100., 1000.],
                            [20., 100., 1000.]          , [20., 100., 1000.]     ]
    ymin_val             : 20.0
    ymax_val             : 1000.

CellObjectType : [
                 PfCand_electron,
                 PfCand_muon,
                 PfCand_chHad,
                 PfCand_nHad,
                 PfCand_gamma,
                 Electron,
                 Muon
                 ]
Features_all :
    TauFlat : [ "tau_pt",
                "tau_eta",
                "tau_phi",
                "tau_mass",
                "tau_E_over_pt",
                "tau_charge",
                "tau_n_charged_prongs",
                "tau_n_neutral_prongs",
                "chargedIsoPtSum",
                "chargedIsoPtSumdR03_over_dR05",
                "footprintCorrection",
                "neutralIsoPtSum",
                "neutralIsoPtSumWeight_over_neutralIsoPtSum",
                "neutralIsoPtSumWeightdR03_over_neutralIsoPtSum",
                "neutralIsoPtSumdR03_over_dR05",
                "photonPtSumOutsideSignalCone",
                "puCorrPtSum",
                "tau_dxy_valid",
                "tau_dxy",
                "tau_dxy_sig",
                "tau_ip3d_valid",
                "tau_ip3d",
                "tau_ip3d_sig",
                "tau_dz",
                "tau_dz_sig_valid",
                "tau_dz_sig",
                "tau_flightLength_x",
                "tau_flightLength_y",
                "tau_flightLength_z",
                "tau_flightLength_sig",
                "tau_pt_weighted_deta_strip",
                "tau_pt_weighted_dphi_strip",
                "tau_pt_weighted_dr_signal",
                "tau_pt_weighted_dr_iso",
                "tau_leadingTrackNormChi2",
                "tau_e_ratio_valid",
                "tau_e_ratio",
                "tau_gj_angle_diff_valid",
                "tau_gj_angle_diff",
                "tau_n_photons",
                "tau_emFraction",
                "tau_inside_ecal_crack",
                "leadChargedCand_etaAtEcalEntrance_minus_tau_eta"
                ]

    PfCand_electron : [
                "pfCand_ele_valid",
                "pfCand_ele_rel_pt",
                "pfCand_ele_deta",
                "pfCand_ele_dphi",
                "pfCand_ele_pvAssociationQuality",
                "pfCand_ele_puppiWeight",
                "pfCand_ele_charge",
                "pfCand_ele_lostInnerHits",
                "pfCand_ele_numberOfPixelHits",
                "pfCand_ele_vertex_dx",
                "pfCand_ele_vertex_dy",
                "pfCand_ele_vertex_dz",
                "pfCand_ele_vertex_dx_tauFL",
                "pfCand_ele_vertex_dy_tauFL",
                "pfCand_ele_vertex_dz_tauFL",
                "pfCand_ele_hasTrackDetails",
                "pfCand_ele_dxy",
                "pfCand_ele_dxy_sig",
                "pfCand_ele_dz",
                "pfCand_ele_dz_sig",
                "pfCand_ele_track_chi2_ndof",
                "pfCand_ele_track_ndof"
                ]

    PfCand_muon : [
              "pfCand_muon_valid",
              "pfCand_muon_rel_pt",
              "pfCand_muon_deta",
              "pfCand_muon_dphi",
              "pfCand_muon_pvAssociationQuality",
              "pfCand_muon_fromPV",
              "pfCand_muon_puppiWeight",
              "pfCand_muon_charge",
              "pfCand_muon_lostInnerHits",
              "pfCand_muon_numberOfPixelHits",
              "pfCand_muon_vertex_dx",
              "pfCand_muon_vertex_dy",
              "pfCand_muon_vertex_dz",
              "pfCand_muon_vertex_dx_tauFL",
              "pfCand_muon_vertex_dy_tauFL",
              "pfCand_muon_vertex_dz_tauFL",
              "pfCand_muon_hasTrackDetails",
              "pfCand_muon_dxy",
              "pfCand_muon_dxy_sig",
              "pfCand_muon_dz",
              "pfCand_muon_dz_sig",
              "pfCand_muon_track_chi2_ndof",
              "pfCand_muon_track_ndof"
              ]

    PfCand_chHad : [
              "pfCand_chHad_valid",
              "pfCand_chHad_rel_pt",
              "pfCand_chHad_deta",
              "pfCand_chHad_dphi",
              "pfCand_chHad_leadChargedHadrCand",
              "pfCand_chHad_pvAssociationQuality",
              "pfCand_chHad_fromPV",
              "pfCand_chHad_puppiWeight",
              "pfCand_chHad_puppiWeightNoLep",
              "pfCand_chHad_charge",
              "pfCand_chHad_lostInnerHits",
              "pfCand_chHad_numberOfPixelHits",
              "pfCand_chHad_vertex_dx",
              "pfCand_chHad_vertex_dy",
              "pfCand_chHad_vertex_dz",
              "pfCand_chHad_vertex_dx_tauFL",
              "pfCand_chHad_vertex_dy_tauFL",
              "pfCand_chHad_vertex_dz_tauFL",
              "pfCand_chHad_hasTrackDetails",
              "pfCand_chHad_dxy",
              "pfCand_chHad_dxy_sig",
              "pfCand_chHad_dz",
              "pfCand_chHad_dz_sig",
              "pfCand_chHad_track_chi2_ndof",
              "pfCand_chHad_track_ndof",
              "pfCand_chHad_hcalFraction",
              "pfCand_chHad_rawCaloFraction"
              ]

    PfCand_nHad : [
              "pfCand_nHad_valid",
              "pfCand_nHad_rel_pt",
              "pfCand_nHad_deta",
              "pfCand_nHad_dphi",
              "pfCand_nHad_puppiWeight",
              "pfCand_nHad_puppiWeightNoLep",
              "pfCand_nHad_hcalFraction"
              ]

    PfCand_gamma : [
              "pfCand_gamma_valid",
              "pfCand_gamma_rel_pt",
              "pfCand_gamma_deta",
              "pfCand_gamma_dphi",
              "pfCand_gamma_pvAssociationQuality",
              "pfCand_gamma_fromPV",
              "pfCand_gamma_puppiWeight",
              "pfCand_gamma_puppiWeightNoLep",
              "pfCand_gamma_lostInnerHits",
              "pfCand_gamma_numberOfPixelHits",
              "pfCand_gamma_vertex_dx",
              "pfCand_gamma_vertex_dy",
              "pfCand_gamma_vertex_dz",
              "pfCand_gamma_vertex_dx_tauFL",
              "pfCand_gamma_vertex_dy_tauFL",
              "pfCand_gamma_vertex_dz_tauFL",
              "pfCand_gamma_hasTrackDetails",
              "pfCand_gamma_dxy",
              "pfCand_gamma_dxy_sig",
              "pfCand_gamma_dz",
              "pfCand_gamma_dz_sig",
              "pfCand_gamma_track_chi2_ndof",
              "pfCand_gamma_track_ndof"
              ]

    Electron : [
              "ele_valid",
              "ele_rel_pt",
              "ele_deta",
              "ele_dphi",
              "ele_cc_valid",
              "ele_cc_ele_rel_energy",
              "ele_cc_gamma_rel_energy",
              "ele_cc_n_gamma",
              "ele_rel_trackMomentumAtVtx",
              "ele_rel_trackMomentumAtCalo",
              "ele_rel_trackMomentumOut",
              "ele_rel_trackMomentumAtEleClus",
              "ele_rel_trackMomentumAtVtxWithConstraint",
              "ele_rel_ecalEnergy",
              "ele_ecalEnergy_sig",
              "ele_eSuperClusterOverP",
              "ele_eSeedClusterOverP",
              "ele_eSeedClusterOverPout",
              "ele_eEleClusterOverPout",
              "ele_deltaEtaSuperClusterTrackAtVtx",
              "ele_deltaEtaSeedClusterTrackAtCalo",
              "ele_deltaEtaEleClusterTrackAtCalo",
              "ele_deltaPhiEleClusterTrackAtCalo",
              "ele_deltaPhiSuperClusterTrackAtVtx",
              "ele_deltaPhiSeedClusterTrackAtCalo",
              "ele_mvaInput_earlyBrem",
              "ele_mvaInput_lateBrem",
              "ele_mvaInput_sigmaEtaEta",
              "ele_mvaInput_hadEnergy",
              "ele_mvaInput_deltaEta",
              "ele_gsfTrack_normalizedChi2",
              "ele_gsfTrack_numberOfValidHits",
              "ele_rel_gsfTrack_pt",
              "ele_gsfTrack_pt_sig",
              "ele_has_closestCtfTrack",
              "ele_closestCtfTrack_normalizedChi2",
              "ele_closestCtfTrack_numberOfValidHits"
              ]

    Muon : [
              "muon_valid",
              "muon_rel_pt",
              "muon_deta",
              "muon_dphi",
              "muon_dxy",
              "muon_dxy_sig",
              "muon_normalizedChi2_valid",
              "muon_normalizedChi2",
              "muon_numberOfValidHits",
              "muon_segmentCompatibility",
              "muon_caloCompatibility",
              "muon_pfEcalEnergy_valid",
              "muon_rel_pfEcalEnergy",
              "muon_n_matches_DT_1",
              "muon_n_matches_DT_2",
              "muon_n_matches_DT_3",
              "muon_n_matches_DT_4",
              "muon_n_matches_CSC_1",
              "muon_n_matches_CSC_2",
              "muon_n_matches_CSC_3",
              "muon_n_matches_CSC_4",
              "muon_n_matches_RPC_1",
              "muon_n_matches_RPC_2",
              "muon_n_matches_RPC_3",
              "muon_n_matches_RPC_4",
              "muon_n_hits_DT_1",
              "muon_n_hits_DT_2",
              "muon_n_hits_DT_3",
              "muon_n_hits_DT_4",
              "muon_n_hits_CSC_1",
              "muon_n_hits_CSC_2",
              "muon_n_hits_CSC_3",
              "muon_n_hits_CSC_4",
              "muon_n_hits_RPC_1",
              "muon_n_hits_RPC_2",
              "muon_n_hits_RPC_3",
              "muon_n_hits_RPC_4"
              ]

Features_disable :
    TauFlat : [ ]
    PfCand_electron : [ ]
    PfCand_muon : [ ]
    PfCand_chHad : [ ]
    PfCand_nHad : [ ]
    PfCand_gamma : [ ]
    Electron : [ ]
    Muon : [ ]
